# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://xjtushilei.github.io
date_format: "ordinal"
title_head: ScriptShi
title: ScriptShi
subtitle: "life and work and learning"
description: "石磊(xjtushilei)的个人博客"
keywords: 石磊,西安交通大学, xjtushilei, ScriptShi
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: ScriptShi
organization: Shaanxi Key Lab. of Satellite-Terrestrial Network Tech. R&D.
organization_url: http://labs.xjtudlc.com/labs/index.html
location: Xi'an, China
email: me@xjtushilei.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: categories

  -
    href: /open-source/
    label: Projects

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xjtushilei/xjtushilei.github.io
# ---------------- #
#      Socials     #
# ---------------- #
github_username: xjtushilei

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-89949079-1

# ---------------- #
#      Datas       #
# ---------------- #

Back_end: [Java, Python, Go, Mysql, MongoDB, Redis, Etcd, Spring Family Bucket, RPC, Docker, DevOps, Operation, System Architecture, ElasticSearch, Weixin, Keras, Distributed system]
Fore_end: [Html5, Js, Jquery, AngularJS, Vue, Bootstrap, Echarts, D3, Android]
Professional_Background: [Knowledge Graph, Sparql, Search, Natural Language Processing, Machine Learning, Deep Learning, WordEmbedding, Distributed system]
