# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.xjtushilei.com
date_format: "ordinal"
title_head: 石磊
title: Shilei
subtitle: "代码改变人生！"
description: "石磊的个人博客"
keywords: 石磊, 郭朝彤, 西安交通大学, 交大吴奇隆
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shilei
organization: Shaanxi Key Lab. of Satellite-Terrestrial Network Tech. R&D.
organization_url: http://labs.xjtudlc.com/labs/index.html
location: Xi'an, China
email: xjtushilei@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: categories

  -
    href: /open-source/
    label: Projects

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xjtushilei/xjtushilei.github.io
# ---------------- #
#      Socials     #
# ---------------- #
github_username: xjtushilei
# douban_username: freedim
# facebook_username: mzlogin
# weibo_username: mzlogin
# zhihu_username: mzlogin
# twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo,sohu
comments_provider: sohu
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: xjtushilei
sohu_userkey: 在代码中实现！这里不用写。直接复制官网js代码！
# disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-89949079-1

# ---------------- #
#      Datas       #
# ---------------- #

Back_end: [Java, Python, Nodejs, Mysql etc., MongoDB etc., Spring Family Bucket, System Architecture, Power Design, ElasticSearch, Weixin, Keras]
Fore_end: [Html5, Js, Jquery, Angular, Vue, Bootstrap, Echarts, D3, Android]
skill_software_keywords: [Linux, Windows server, Apache, Nigix, Tomcat, Maven, Gradle, Git, IDEA]
Professional_Background: [Knowledge Graph, Sparql, Search, Natural Language Processing, Machine Learning, Deep Learning]

