# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://shilei.link
date_format: "ordinal"
title: 石磊
subtitle: "代码改变人生"
description: "石磊的个人博客"
keywords: 石磊, 郭朝彤, 西安交通大学, 交大吴奇隆
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 石磊
organization: 陕西省天地网技术重点实验室.
organization_url: http://labs.xjtudlc.com/labs/index.html
location: Xi'an, China
email: xjtushilei@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /open-source/
    label: 项目

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xjtushilei/xjtushilei.github.io
# ---------------- #
#      Socials     #
# ---------------- #
github_username: xjtushilei
# douban_username: freedim
# facebook_username: mzlogin
# weibo_username: mzlogin
# zhihu_username: mzlogin
# twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: xjtushilei
# disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-89949079-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, Html/Js, C++, Nosql,ElasticSearch]
skill_mobile_app_keywords: [Android, Html5]
skill_windows_keywords: [Windows server, Apache, Nigix, Office]
